Ako/ Init project with Vite, Semantic Release and R2 upload workflow
deriv-com/webflow-deriv-com-scripts pull request #1
Opened 2024-06-12 10:01 UTC by ali-hosseini-deriv

1. Added the project structure to build the `css` and `js` into their respective directories in `dist` folder.
2. Added semantic release for automatic versioning.
3. Added a github action to upload the built files to R2 bucket and create a directory for each semantic release version.

2024-06-12 10:43 UTC, shayan-deriv commented on src/js/footer/index.js
> +// All the header js files should be imported and exported from here
```suggestion
// All the footer js files should be imported and exported from here
```

2024-06-12 10:52 UTC, yashim-deriv approved these changes

2024-06-12 10:57 UTC, shayan-deriv approved these changes

2024-06-12 12:52 UTC, dan-deriv requested changes
Let us please have the following executed:

1. integrate existing code into the PR
2. bundle JS into a single file
3. Confirm that artifact can be imported and runs fine in test branch for webflow.deriv.com

2024-06-13 07:54 UTC, dan-deriv approved these changes
As agreed with @ali-hosseini-deriv footer-code will be transitioned from Webflow into Git and proposed workflow confirmed.

2024-06-13 08:50 UTC, merged